---
  - host: puplicEC2-1
    remote-user: ubuntu
    become: yes
    tasks:
    - name: Copy private key to EC2
      copy:
        src: ~/terraform-project-web/key-pair.pem
        dest: /home/ubuntu/key-pair.pem
        mode: '0600'
    - name: apt-update
      apt:
        update_cache: yes
    # tasks/main.yml
    - name: Install Ansible
      apt:
        name: ansible
        state: latest
      become: yes
    - name: Copy inventory to EC2
      copy:
        src: ~/terraform-project-web/private-ansible-code-1/inventory
        dest: /home/ubuntu/inventory
        mode: '0644'
    - name: Copy private playbook.yaml to EC2
      copy:
        src: ~/terraform-project-web/private-ansible-code-1/private_playbook.yaml
        dest: /home/ubuntu/private_playbook.yaml
        mode: '0644'
    - name: ssh to be authrized
      command: "ssh-i key-pair.pem ubuntu@"  #put ip of private instance  
    - name: exit
      command: "exit"  
      # - name: copy docker installation script      
      # copy:
      #   src: ~/terraform-project-web/private-ansible-code-1/docker.sh
      #   dest: /home/ubuntu/docker.sh
      #   mode: '0644' 
    # - name: Install Docker
    #   apt:
    #     name: docker.io
    #     state: present
    #     update_cache: yes

    # - name: Ensure Docker service is running
    #   service:
    #     name: docker
    #     state: started
    #     enabled: yes

    # - name: Run NGINX container
    #   docker_container:
    #     name: nginx
    #     image: nginx
    #     state: started
    #     ports:
    #       - "80:80"